# Generated by Django 3.0.6 on 2020-05-04 11:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttrKey',
            fields=[
                ('attr_key_id', models.AutoField(primary_key=True, serialize=False)),
                ('attr_name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttrValue',
            fields=[
                ('attr_val_id', models.AutoField(primary_key=True, serialize=False)),
                ('attr_value', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('attr_key_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.AttrKey')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('bnd_id', models.AutoField(primary_key=True, serialize=False)),
                ('bnd_name', models.CharField(max_length=20)),
                ('bnd_code', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pdt_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdt_name', models.CharField(max_length=20)),
                ('pdt_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pdt_desc', models.TextField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecs',
            fields=[
                ('pdt_spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdt_spec_name', models.CharField(blank=True, max_length=20, null=True)),
                ('pdt_spec_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pdt_spec_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('pdt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecsToAttrVal',
            fields=[
                ('pdt_specs_attr_val_id', models.AutoField(primary_key=True, serialize=False)),
                ('attr_val_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.AttrValue')),
                ('pdt_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSpecs')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=20)),
                ('cat_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('attr_list', models.ManyToManyField(to='product.AttrKey')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='attrkey',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
    ]
