# Generated by Django 3.0.6 on 2020-05-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecs',
            name='pdt_spec_name',
            field=models.CharField(max_length=20),
        ),
    ]
